controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

api_platform:
    resource: .
    type: api_platform
    prefix: /api    
